### ISSUE TITLE
Verbose mode for -emit-expr

### ISSUE THREAD

**Issue by ryukinix** [luizperes/brain#2]
Maybe can be useful get a more descriptive and friendly the expressions of `-emit-expr`. The idea is put things like `IncrementExpr (3)` as `IncrementExpression 3 times in cell x`.

**Comment by luizperes** [comment]
Thanks! New feature has just been implemented [here](https://github.com/luizperes/brain/commit/f190191ea4fe9b284d15902a0ee7dbe3a69651f1)

Code:
```Brainfuck
+++>++*
```

Representation:
![verbosity](https://cloud.githubusercontent.com/assets/6173065/16544927/53b2b63a-40cc-11e6-84af-9eee359dea00.png)

How is it?

**Comment by ryukinix** [comment]
Very very good! Congratulations, @luizperes ! <3 I love it

**Comment by luizperes** [comment]
Thanks! I also changed from -emit-expr to -emit-ast :)

**Comment by ryukinix** [comment]
Nice! <3
