### ISSUE TITLE
Implementation of the symbol `$`

### ISSUE THREAD

**Issue by luizperes** [luizperes/brain#5]
Initially I was thinking about using the char `$` for converting the current cell back and forth with `float` and `int`, that would have some implications with the `LLVM IRBuilder`, since we would need to implement suppport to `floating numbers` for each arithmetic operation, debug and so on... Although, my real concerns are related on how we would do it... I was thinking of using `union` for that

**Comment by luizperes** [comment]
@ryukinix @rafaelcn

**Comment by luizperes** [comment]
There is another approach in [here](http://stackoverflow.com/questions/10067510/fixed-point-arithmetic-in-c-programming). What do you think?

**Comment by luizperes** [comment]
Having this link http://stackoverflow.com/questions/10067510/fixed-point-arithmetic-in-c-programming in my, we will have the operator `$` as a __print__ function, just like one would do: 
```C
printf("%.2f", value / 100.0);
```
In this way, we would create a library for the use of the FPU.

**Comment by rafaelcn** [comment]
We already have a library (`io.c`), should we implement a function with that behavior you mentioned?

**Comment by luizperes** [comment]
Yes @rafaelcn! :) as `io.c` file already exists and the `FloatExpr` is purely __IO__ for now, I think that this should be the best approach regarding our architecture. Thanks!

**Comment by rafaelcn** [comment]
[Implementation completed](https://github.com/rafaelcn/brain/tree/floatexpr). Now I just need to implement the tests.

**Comment by luizperes** [comment]
Looks very good!!!! Can you add the test files to it and send a PR? 

Thanks :D 👍🏾👍🏾👍🏾

**Comment by rafaelcn** [comment]
Sure, on my way to do it! :dancer:

**Comment by rafaelcn** [comment]
Done, for more info see #20.
