### ISSUE TITLE
Implementation of a pre-processor

### ISSUE THREAD

**Issue by luizperes** [luizperes/brain#6]
I would like to get some pros and cons related to the use of a pre-processor on Brain. Any suggestions?

**Comment by luizperes** [comment]
@ryukinix @rafaelcn

**Comment by ryukinix** [comment]
Which cases you think pre-processing can be really necessary & useful with brainfuck?

**Comment by luizperes** [comment]
@ryukinix using macros to have the possibility to "extend" the language/ make repetitive tasks easier

**Comment by ryukinix** [comment]
Macros are really nice, but how you wish implement this? C-like syntax with `#define` ?

**Comment by luizperes** [comment]
Yeah, C-style(ish) macro...
I imagine that we can do that by using pipes.
Example:

```Brainfuck
| +++++ |
```

Each pipe would have a number related to it... Inside the code we would call the macros like:

```Brainfuck
+ make number 1 because is the first macro
^ call macro
```

In this case we would need two more operators `|` and `^`, which is bad. Do you have pros and cons?

**Comment by luizperes** [comment]
@ryukinix I was thinking of changing a bit the code above... What if it was like that?

```Brainfuck
| number_five +++++ |
| arithmetic.brain |
```

In the first case, I'm creating a macro called `number_five`, in the second case, I'm including a file. What do you think? In this case we only need the operator pipe `|`

**Comment by rafaelcn** [comment]
Discussing about this feature with @luizperes in a call was revealing, while this is a nice idea it brings a bit of complexity to Brain (As it was not complex enough [literal joke here]), adding operators expands the range of errors that we could possibly get that's one of the drawbacks, we just have to study carefully when and how to implement this great feature!

**Comment by luizperes** [comment]
@ryukinix @rafaelcn Thinking and re-thinking, I realized that what @rafaelcn made so much sense. We should not add more complexity (more than planned) on Brain. As we want to use this language to solve AI problems as well, I do not think that we should add this new `layer` of complexity. Well, pointed @rafaelcn .

**Comment by luizperes** [comment]
Anyone is welcome to re-open this discussion.
