### ISSUE TITLE
Representing numbers in Brain

### ISSUE THREAD

**Issue by luizperes** [luizperes/brain#8]
I'm opening this new thread because __Brain__ needs to represent literal numbers in a better way than __Brainfuck__. How can we do that?

I have seen some languages doing (and @leonardohn has also suggested to use)
```Brainfuck
5+4---->3*
```
Although that would make us implement __at least__ 10 more commands `0-9` and they would not be one byte commands anymore. Because of that, I'm thinking of a new way of representing numbers in a cheap way.

For example, image the number `123`. How would one represent that in Brain?

```Brainfuck
+++++++++++ make number 11 on cell 0
> + make number 1 on cell 1 
* make number 11 on the next cell
* multiply cells 0 and 1 = 121
++ add 2 on cell 1
```

For that, I think that we should think on a new and faster way (that wouldn't create more commands). For example:
```Brainfuck
+    step 1 \ make number 1 on cell 0
>++ step 2 \ make number 2 on cell 1
>+++ step 3 \ make number 3 on cell 2
<<< step 4 \ return to cell 0
$ step 5 \ eval the number and write it on cell 4
```
In that way, `$` would work as an eval for a number (making the literal number), in this way:

- Step 1: `[1][0][0][0][0]...`
- Step 2: `[1][2][0][0][0]...`
- Step 3: `[1][2][3][0][0]...`
- Step 4: `[1][2][3][0][0]...`
- Step 5: `[1][2][3][123][0]...` _// evaluates until it find a '0' and replace it with the number found_

What do you guys think?

**Comment by luizperes** [comment]
@ryukinix @leonardohn @rafaelcn

**Comment by ryukinix** [comment]
Very very interesting, I will take time later to discuss this more deeply.

**Comment by luizperes** [comment]
I think that this feature would not be a good approach for this project, because we would have to create a `command` that would depend on multiple cells, bringing more complexity to the project, reminded by @rafaelcn on a discussion https://github.com/luizperes/brain/issues/6. I imagine that we can go on complexity up to two operands. (`ArithmeticExpr-like`).

A good approach would be using external functions for that, as described here https://github.com/luizperes/brain/issues/8

**Comment by luizperes** [comment]
Anyone is welcome to re-open this discussion
